Formatting Number Fix
brumik/react-json-chart-builder pull request #41
Opened 2021-07-27 23:34 UTC by knightsean00

https://issues.redhat.com/browse/AA-640

2021-07-28 09:52 UTC, brumik requested changes
Can you please make the demo data with a positive cumulative value too? Having only negative ones does not really reflect the expected use case.

Btw: was this feature requested somewhere?

2021-07-28 09:52 UTC, brumik commented on src/components/Functions/axisFormat.ts
> +    if (+n === 0) {
The preferred method to convert something to string is  `{stringVar}`. Can we use it here too (and bellow).

I prefer having a single return statement without `{` and `}` inlined.

2021-07-28 17:54 UTC, knightsean00 commented
> Can you please make the demo data with a positive cumulative value too? Having only negative ones does not really reflect the expected use case.
> 
> Btw: was this feature requested somewhere?

2021-07-29 07:20 UTC, brumik commented on src/components/Functions/axisFormat.ts
> +    const remainLen = 3 - `${output.toFixed(0)}`.length + (output > 0 ? 0 : 1);
I now understand the number `3` at the start of the row, can we move it to a constant and name it appropriately so it is easier to read?

2021-07-29 07:22 UTC, brumik commented
I made the function to return to 1 decimal point the digits, since in cases where the range is going by for example 500 you would only get 0, 500, 1k, 1k, 2k which is not ideal. If we do millions then it is the same in the higher range where you can possibly get after each other in the label the same number. As I seen the issue they don't think about it. I would suggest to have 4 or 5 digists where the last or last two digits are decimal spaces so we get with much smaller chance the same labels for two different spots.

2021-07-29 17:34 UTC, knightsean00 commented
> I made the function to return to 1 decimal point the digits, since in cases where the range is going by for example 500 you would only get 0, 500, 1k, 1k, 2k which is not ideal. 

In this case, you would get 0, 500, 1k, 1.5k, and 2k which I think works fine?

> I would suggest to have 4 or 5 digists where the last or last two digits are decimal spaces so we get with much smaller chance the same labels for two different spots.

That should be fine because if our scale is large, then three sig figs are more than enough to differentiate as long as we have a large range (e.g. I don't think we would ever have a graph where the tick marks would just be small variations of 2M)

2021-07-31 19:03 UTC, brumik approved these changes
Okey, I see. If there will be a graph with a small variability over big number we can just revisit this function then :)

2021-07-31 19:03 UTC, merged